import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

/**
 * Bootstrap seed: base subjects, package templates and the first staff
 * accounts for an EMPTY database. It is safe to run on every deploy:
 *
 * - If the database already has users or students it does nothing.
 * - It wipes existing data only when ALLOW_DB_RESET="wipe-all-data" is set
 *   (never leave that set: every run would delete all records).
 * - In production the staff password must come from SEED_ADMIN_PASSWORD
 *   (12+ characters); the public demo password is used only locally.
 */
const RESET_PHRASE = "wipe-all-data";

function initialPassword(): string {
  const fromEnv = process.env.SEED_ADMIN_PASSWORD ?? "";
  if (process.env.NODE_ENV === "production") {
    if (fromEnv.length < 12 || fromEnv === "demo123") {
      throw new Error("Set SEED_ADMIN_PASSWORD (12+ characters) to create the first staff accounts in production.");
    }
    return fromEnv;
  }
  return fromEnv || "demo123";
}

async function wipeAllData() {
  await prisma.auditLog.deleteMany();
  await prisma.parentConcern.deleteMany();
  await prisma.assessment.deleteMany();
  await prisma.studentProgress.deleteMany();
  await prisma.payoutItem.deleteMany();
  await prisma.payoutRun.deleteMany();
  await prisma.followUp.deleteMany();
  await prisma.paymentAllocation.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.invoiceInstalment.deleteMany();
  await prisma.invoiceLineItem.deleteMany();
  await prisma.invoice.deleteMany();
  await prisma.attendanceRevision.deleteMany();
  await prisma.attendanceRecord.deleteMany();
  await prisma.session.deleteMany();
  await prisma.timetableSlot.deleteMany();
  await prisma.idempotencyKey.deleteMany();
  await prisma.creditLedger.deleteMany();
  await prisma.subjectAllocation.deleteMany();
  await prisma.studentPackage.deleteMany();
  await prisma.packageTemplate.deleteMany();
  await prisma.subjectEnrollment.deleteMany();
  await prisma.student.deleteMany();
  await prisma.guardian.deleteMany();
  await prisma.user.deleteMany();
  await prisma.teacher.deleteMany();
  await prisma.subject.deleteMany();

  console.log("🧹 Cleaned existing tables.");
}

async function main() {
  const [users, students] = await Promise.all([prisma.user.count(), prisma.student.count()]);
  const resetRequested = true; // FORCING WIPE UNTIL REVERTED
  if ((users > 0 || students > 0) && !resetRequested) {
    console.log(`ℹ️  Database already initialised (${users} users, ${students} students). Seed skipped; nothing was changed.`);
    return;
  }
  const password = initialPassword();
  if (resetRequested) {
    console.warn(`⚠️  ALLOW_DB_RESET=${RESET_PHRASE}: deleting ALL existing records. Remove this setting after this run.`);
    await wipeAllData();
  }
  console.log("🌱 Starting Xello Tuition initialisation...");


  // 2. Base Subjects
  await prisma.subject.createMany({
    data: [
      { id: "sub-chem", name: "Chemistry", code: "CHEM", category: "Science", color: "#0284c7" },
      { id: "sub-eng", name: "English", code: "ENG", category: "Languages & Literature", color: "#16a34a" },
      { id: "sub-math", name: "Mathematics", code: "MATH", category: "STEM", color: "#7c3aed" },
      { id: "sub-phy", name: "Physics", code: "PHY", category: "Science", color: "#ea580c" },
      { id: "sub-bio", name: "Biology", code: "BIO", category: "Science", color: "#059669" },
    ],
  });

  console.log("✅ Seeded Base Subjects.");

  // 3. Package Templates
  await prisma.packageTemplate.createMany({
    data: [
      {
        id: "pkg-gcc-standard",
        name: "Standard GCC Package",
        totalCredits: 12,
        durationMinutes: 60,
        defaultPrice: 850,
        currency: "AED",
        notes: "12 hours per month across multiple subjects for GCC curriculum."
      },
      {
        id: "pkg-kerala-flex",
        name: "Kerala Board Flexi-Pack",
        totalCredits: 20,
        durationMinutes: 60,
        defaultPrice: 12000,
        currency: "INR",
        notes: "20 hours total, no expiry, for intense exam prep across subjects."
      },
    ],
  });
  console.log("✅ Seeded Base Package Templates.");

  // 4. Admin Users
  const passwordHash = await bcrypt.hash(password, 12);

  await prisma.user.createMany({
    data: [
      {
        id: "usr-admin",
        name: "Shamrood",
        email: "admin@xellotuition.com",
        role: "OWNER",
        passwordHash,
      },
      {
        id: "usr-coord",
        name: "Aisha Nair (Academic Coordinator)",
        email: "coordinator@xellotuition.com",
        role: "COORDINATOR",
        passwordHash,
      },
      {
        id: "usr-accounts",
        name: "Joseph Thomas (Accounts Manager)",
        email: "accounts@xellotuition.com",
        role: "ACCOUNTS",
        passwordHash,
      },
    ],
  });
  console.log("✅ Seeded Admin & Coordinator Users.");
  

  // 5. Trainers
  await prisma.teacher.createMany({
    data: [
  {
    name: "Maha SulaimaN",
    email: "mahasulaiman99@gmail.com",
    phone: "9061943670",
    subjects: "Mathematics",
    grades: "8 -plus 2",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Nishana K L",
    email: "nishana.nichu015@gmail.com",
    phone: "7909224110",
    subjects: "Physics",
    grades: "+1 +2 degree",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Shilpa Krishnan",
    email: "shilpakrishnan2511@gmail.com",
    phone: "8590830775",
    subjects: "English",
    grades: "8,9,10, +1, +2",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Ayesha Siddiqa",
    email: "ayeshasiddiqa7650@gmail.com",
    phone: "9845695446",
    subjects: "Biology",
    grades: "Class 8 - Class 12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "NADEERA K P",
    email: "saleemnadeera8899@gmail.com",
    phone: "7510914741",
    subjects: "Hindi, Maths, Social science & Chemistry",
    grades: "9 & 10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Hibanourin K K",
    email: "hibanourin.98@gmail.com",
    phone: "9447909621",
    subjects: "Chemistry",
    grades: "HS, HSST",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Jasna vallanchira",
    email: "jasnaramiz@gmail.com",
    phone: "7356096323",
    subjects: "Social science, English",
    grades: "1 to 10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Nawar",
    email: "nawa@gmail.com",
    phone: "9946856229",
    subjects: "Mathematics, English",
    grades: "6 to 10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Neha Nazeer",
    email: "nehanazdxb@gmail.com",
    phone: "7356331044",
    subjects: "Chemistry",
    grades: "9,10,11 and 12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Thabsheera Shery P",
    email: "nb151158@gmail.com",
    phone: "9074584764",
    subjects: "Maths",
    grades: "1-10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Shameema P",
    email: "pshameema260@gmail.com",
    phone: "9562537430",
    subjects: "Biology (Botony&Zoology) Hindi, Chemistry",
    grades: "6-12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Ayisha finu",
    email: "ayshafinu20@gmail.com",
    phone: "8078261328",
    subjects: "Mathematics",
    grades: "1 to 10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Fathimathu Shahara",
    email: "fathimathushahara404134@gamil.com",
    phone: "9633952640",
    subjects: "Biology,Chemistry",
    grades: "8,9&10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "RAJITHA PV",
    email: "rajithapv1234@gmail.com",
    phone: "9400038649",
    subjects: "Teach both Biology and Chemistry for 9&10th and General Science from grade 6-8 classes",
    grades: "6 to 10th",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "IHSAN KC",
    email: "kcihsan@gmail.com",
    phone: "9544089076",
    subjects: "Chemistry",
    grades: "10-12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Ranjitha c",
    email: "ranjitharanjuraj19@gmail.com",
    phone: "7025356127",
    subjects: "Physics and chemistry",
    grades: "7 to +2",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Fathima Febi E",
    email: "febiefathima@gmail.com",
    phone: "9074531210",
    subjects: "All subject",
    grades: "1-10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Aswathy.A",
    email: "aswathyasokan002@gmail.com",
    phone: "8592027791",
    subjects: "Malayalam",
    grades: "1 to 10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Fathima Ifna",
    email: "fathima.ifna90@gmail.com",
    phone: "9061358003",
    subjects: "Biology",
    grades: "+1&+2",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "ASWATHI B",
    email: "aswathibiju425@gmail.com",
    phone: "9074450683",
    subjects: "English and Social science",
    grades: "5 to +2",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Ashna Rajeevan",
    email: "ashnarajeevan241@gmail.com",
    phone: "8547013677",
    subjects: "Physics",
    grades: "7 to plus 2",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Zanha Meharin",
    email: "meharinzanha@gmail.com",
    phone: "7666843494",
    subjects: "Hindi",
    grades: "Till class 10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Farhana Sherin",
    email: "farhanasherin8808@gmail.com",
    phone: "8589880865",
    subjects: "Computer application",
    grades: "High school and higher secondary",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Nithin Kumar Rai R",
    email: "nithinkumarrai99@gmail.com",
    phone: "7356098771",
    subjects: "Mathematics",
    grades: "Class 5 to 12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Vafa Pv",
    email: "pv.vafa@gmail.com",
    phone: "7902452695",
    subjects: "Arabic & Social science",
    grades: "1 to 10 std",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Shameema tk",
    email: "shameematk1000@gmail.com",
    phone: "7012093876",
    subjects: "Hindi",
    grades: "Kg to 10th",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Aswani P",
    email: "aswanivas2807@gmail.com",
    phone: "9961597896",
    subjects: "Physics , Social Science",
    grades: "Grade 1-7 all subjects and High school Physics Social and Biology",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Nihal Moideen CTP",
    email: "nmcwdr@gmail.com",
    phone: "+918075700853",
    subjects: "Zoology, Biology",
    grades: "10-12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Asma M",
    email: "asma.muthuvana@gmail.com",
    phone: "9946364360",
    subjects: "Maths",
    grades: "10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "ANJANA A",
    email: "anjanarajendran7620@gmail.com",
    phone: "9745624823",
    subjects: "Science",
    grades: "UP,HS,HSS",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Riswana Narkkees S",
    email: "riswananarkkeesskd1234@gmail.com",
    phone: "8547197263",
    subjects: "Primary students all subject except Hindi",
    grades: "4-7",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "SNEHA S NAIR",
    email: "snehasnair200@gmail.com",
    phone: "8281521358",
    subjects: "Maths,Physics,Biology,Computer Science,Coding",
    grades: "Till class 10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "MARIYA BENNY K",
    email: "mariyabennyk2325@gmail.com",
    phone: "7736752899",
    subjects: "Mathematics",
    grades: "Class 6,7, 8, Class 11",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Vipanya k",
    email: "vipanyak02@gmail.com",
    phone: "9539501019",
    subjects: "Physics",
    grades: "Up, hs, hss",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Sreelakshmi KS",
    email: "sreelakshmiksmenon@gmail.com",
    phone: "8137983347",
    subjects: "Maths",
    grades: "Highschool and higher secondary",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Adithya",
    email: "id4adithya@gmail.com",
    phone: "6238958133",
    subjects: "Hindi",
    grades: "1 to 9",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Fathima husna kp",
    email: "fathimahusnakp67@gmail.com",
    phone: "7012134417",
    subjects: "Science and social science",
    grades: "High school, Higher secondary",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Gayatri Mukhi",
    email: "gayatrimukhibluebell@gmail.com",
    phone: "7990704159",
    subjects: "French, science, english, hindi, sanskrit",
    grades: "1-12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Akhila. V",
    email: "akhilamaya02@gmail.com",
    phone: "7902252628",
    subjects: "Socialscience and malayalam",
    grades: "5 to 8",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Ramseena",
    email: "ramseenashaijal82@gmail.com",
    phone: "9961342360",
    subjects: "Maths",
    grades: "5-12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "SHAHANA PARVEEN",
    email: "shahanaparveen212@gmail.com",
    phone: "9496919855",
    subjects: "Arabic",
    grades: "KG to 8",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Aparna",
    email: "aparnaappu64557@gmail.com",
    phone: "9633356431",
    subjects: "Social science ( also all subjects)",
    grades: "5- 12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Arsha P",
    email: "arshap2006@gmail.com",
    phone: "9656055985",
    subjects: "Social science,Basic science",
    grades: "Upto class 12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Sandra vp",
    email: "sandrarajesh92@gmail.com",
    phone: "8281405158",
    subjects: "English",
    grades: "1- 10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "SAMVRIDHA SUNIL",
    email: "samvridha2004@gmail.com",
    phone: "9497476914",
    subjects: "Maths",
    grades: "4-7",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Fathima hiba",
    email: "fathimahibafhb@gmail.com",
    phone: "9447919482",
    subjects: "Mathematics",
    grades: "KG to 10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Shamla",
    email: "shamlanizam1914@gmail.com",
    phone: "7034661221",
    subjects: "Biology, science, Evs, English",
    grades: "1 - 12 th grades",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Nikita",
    email: "nikitaparmar541@gmail.com",
    phone: "9671544766",
    subjects: "Mathematics",
    grades: "2nd to 12th",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Rinshida MK",
    email: "rinshidamk1@gmail.com",
    phone: "7034280806",
    subjects: "Chemistry(grade:8-10),General science:(grade5-7)",
    grades: "5-10",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Aysha minha",
    email: "nunnununnu2726@gmail.com",
    phone: "8714102409",
    subjects: "English,E.v.s, Hindi, malayalam",
    grades: "Upto 3",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Fathima fidha c",
    email: "fathimafidhanarath@gmail.com",
    phone: "9539220232",
    subjects: "Arabic",
    grades: "Kg to 5th",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Pravya P",
    email: "pravyapprakash004@gmail.com",
    phone: "8075107275",
    subjects: "Chemistry and physics",
    grades: "1 to plus two",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "Anagha S",
    email: "anaghassanil@gmail.com",
    phone: "7594930908",
    subjects: "Chemistry",
    grades: "7-12",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "MURSHIDA SUMAYYA",
    email: "murshidasumi@gmail.com",
    phone: "9847637546",
    subjects: "English, science, arabic, maths",
    grades: "1-7",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  },
  {
    name: "SITHARA PARVEEN",
    email: "sitharaparveen1999@gmail.com",
    phone: "8593942285",
    subjects: "MATHEMATICS",
    grades: "5th to +2",
    country: "India",
    timeZone: "Asia/Kolkata",
    active: true,
    defaultRate: 500,
  }
    ]
  });

  console.log("✅ Seeded Trainers.");


  // 6. Students
  await prisma.student.createMany({
    data: [
  {
    studentCode: "XST-SEED-" + String(1).padStart(3, "0"),
    name: "Rithik p",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(2).padStart(3, "0"),
    name: "Aiden Dinny",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(3).padStart(3, "0"),
    name: "Devna jayesh",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(4).padStart(3, "0"),
    name: "ALAN SHAIJU",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(5).padStart(3, "0"),
    name: "Neda Jamal",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(6).padStart(3, "0"),
    name: "Muhammed Farhan",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(7).padStart(3, "0"),
    name: "Angela Elsa Renju",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(8).padStart(3, "0"),
    name: "Anugraha Umesh C",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(9).padStart(3, "0"),
    name: "AADINATH S",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(10).padStart(3, "0"),
    name: "Fathima A shakeer",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(11).padStart(3, "0"),
    name: "Angelina Sara Tiju",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(12).padStart(3, "0"),
    name: "Aviah",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(13).padStart(3, "0"),
    name: "Ziya Abinawas",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(14).padStart(3, "0"),
    name: "Nabhan",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(15).padStart(3, "0"),
    name: "Zahil Abinavas",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(16).padStart(3, "0"),
    name: "Ayan Anees",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(17).padStart(3, "0"),
    name: "Lazhar kamal",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(18).padStart(3, "0"),
    name: "Mifzal rahan",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(19).padStart(3, "0"),
    name: "Mayookha Prabhu",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(20).padStart(3, "0"),
    name: "Salih Mohamed (maths)",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(21).padStart(3, "0"),
    name: "Prakriti prajin",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(22).padStart(3, "0"),
    name: "Aganaya Sreejith",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(23).padStart(3, "0"),
    name: "Ehaan Anees",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(24).padStart(3, "0"),
    name: "Saarang Arjun",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(25).padStart(3, "0"),
    name: "Muhammad hamdan kasim",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(26).padStart(3, "0"),
    name: "Krithik. C Krishnan",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(27).padStart(3, "0"),
    name: "Siona Sajeesh",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(28).padStart(3, "0"),
    name: "Zain Sajeesh",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(29).padStart(3, "0"),
    name: "Rihan Bin Rafeek",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(30).padStart(3, "0"),
    name: "RYAN MELVIN FERNANDEZ",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(31).padStart(3, "0"),
    name: "Anwita Abhilash",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(32).padStart(3, "0"),
    name: "Diya Harikumar D",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(33).padStart(3, "0"),
    name: "Adline Mariyam Sam",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(34).padStart(3, "0"),
    name: "Asthik manesh",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(35).padStart(3, "0"),
    name: "Tanve C Vijith",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(36).padStart(3, "0"),
    name: "ARUNDHATHI R NAIR",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(37).padStart(3, "0"),
    name: "Reathaj",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(38).padStart(3, "0"),
    name: "Alicia Sara Shiju",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(39).padStart(3, "0"),
    name: "Anshif M",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(40).padStart(3, "0"),
    name: "Evelyn elza George",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(41).padStart(3, "0"),
    name: "Nainika Sreejith",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(42).padStart(3, "0"),
    name: "Eeva Izza Fathima",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(43).padStart(3, "0"),
    name: "Alan Robin",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(44).padStart(3, "0"),
    name: "Ashley JACOB",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(45).padStart(3, "0"),
    name: "Angeline linto",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(46).padStart(3, "0"),
    name: "Hazim Ahamed",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(47).padStart(3, "0"),
    name: "Alan sajo",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(48).padStart(3, "0"),
    name: "RiyanRejish",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(49).padStart(3, "0"),
    name: "Jude Mathews",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(50).padStart(3, "0"),
    name: "Karthikeyan D",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(51).padStart(3, "0"),
    name: "Brindha. R",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(52).padStart(3, "0"),
    name: "Crystal Mary Roy",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(53).padStart(3, "0"),
    name: "Abdulla zainadeen",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(54).padStart(3, "0"),
    name: "Reeshah Haleem",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(55).padStart(3, "0"),
    name: "Munawar Ibrahim",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(56).padStart(3, "0"),
    name: "ABHIRAM ASHOK",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(57).padStart(3, "0"),
    name: "Faiza",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(58).padStart(3, "0"),
    name: "Jenn Riya Sam",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(59).padStart(3, "0"),
    name: "Mohammed yaseen",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(60).padStart(3, "0"),
    name: "Jewel Elizabeth Cyriac",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(61).padStart(3, "0"),
    name: "Erin Jinu George",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(62).padStart(3, "0"),
    name: "SHRUTI POLIN JONES",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(63).padStart(3, "0"),
    name: "RAIBAL JIYO",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(64).padStart(3, "0"),
    name: "Hanna Shanavas",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(65).padStart(3, "0"),
    name: "Muhammed Shebin P",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(66).padStart(3, "0"),
    name: "MYSHA AIYAS AGA",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(67).padStart(3, "0"),
    name: "Liam Ahamed",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(68).padStart(3, "0"),
    name: "Ritvika Vipinkumar",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(69).padStart(3, "0"),
    name: "Vagisha Varun Nair",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(70).padStart(3, "0"),
    name: "Saatvik Arjun",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(71).padStart(3, "0"),
    name: "Joel Antony Alfred",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(72).padStart(3, "0"),
    name: "Abdullah Bin Abu Thahir",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(73).padStart(3, "0"),
    name: "ANLIYA MS",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(74).padStart(3, "0"),
    name: "Vishnu S Viswanath",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(75).padStart(3, "0"),
    name: "Rihan Subair",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(76).padStart(3, "0"),
    name: "Nehal Vimal Dev",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(77).padStart(3, "0"),
    name: "NS Karthik",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(78).padStart(3, "0"),
    name: "Aptha Ratheesh",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(79).padStart(3, "0"),
    name: "Fathima Anjoom",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(80).padStart(3, "0"),
    name: "Mohammad hanan. V",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(81).padStart(3, "0"),
    name: "Fathima aina. V",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(82).padStart(3, "0"),
    name: "Siya Fathima Sanis",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(83).padStart(3, "0"),
    name: "Rayan Shamseer",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(84).padStart(3, "0"),
    name: "Zainab Shamseer",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(85).padStart(3, "0"),
    name: "Adhrit poonoth",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(86).padStart(3, "0"),
    name: "Rahul B Mohan",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(87).padStart(3, "0"),
    name: "Aafreen Fathima",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(88).padStart(3, "0"),
    name: "Alna Theresa Vibin",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(89).padStart(3, "0"),
    name: "EBIN SEBASTIAN",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(90).padStart(3, "0"),
    name: "Adwika Deepu",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(91).padStart(3, "0"),
    name: "Sayyid Ahmad Fazal",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(92).padStart(3, "0"),
    name: "Janoah Varghese Tinu",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(93).padStart(3, "0"),
    name: "Ayisha Ezrin",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(94).padStart(3, "0"),
    name: "Sara susan ronny",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(95).padStart(3, "0"),
    name: "Azza Mehak A. A",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(96).padStart(3, "0"),
    name: "Maryam Nizam arabic",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(97).padStart(3, "0"),
    name: "Joseph George kottayil",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(98).padStart(3, "0"),
    name: "Yara Zainab",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(99).padStart(3, "0"),
    name: "Maryam",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(100).padStart(3, "0"),
    name: "Adharv Sony",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(101).padStart(3, "0"),
    name: "Delna Vinu",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(102).padStart(3, "0"),
    name: "Anand krishna.p",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(103).padStart(3, "0"),
    name: "Josh N Nidhiry",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(104).padStart(3, "0"),
    name: "AADHISANKAR",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(105).padStart(3, "0"),
    name: "ANVITHA SARATH",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(106).padStart(3, "0"),
    name: "Sainika Ragupathy",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(107).padStart(3, "0"),
    name: "Ayisha",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(108).padStart(3, "0"),
    name: "Neha. T",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(109).padStart(3, "0"),
    name: "Tanvika Vipin",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(110).padStart(3, "0"),
    name: "Ishaan R Kumar",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(111).padStart(3, "0"),
    name: "vishnu dev.m",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(112).padStart(3, "0"),
    name: "Karthik jayesh",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(113).padStart(3, "0"),
    name: "DANIEL JACOB JOY",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(114).padStart(3, "0"),
    name: "Aiden Thomas Manu",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(115).padStart(3, "0"),
    name: "MUHAMMED ISMAIL",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(116).padStart(3, "0"),
    name: "Catherine Pratheesh",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(117).padStart(3, "0"),
    name: "Jaslyn Rathna",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(118).padStart(3, "0"),
    name: "Saketh Sanal",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(119).padStart(3, "0"),
    name: "Catherine Maria Benny",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(120).padStart(3, "0"),
    name: "Ann Anna Paul",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(121).padStart(3, "0"),
    name: "Dharmika SA",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(122).padStart(3, "0"),
    name: "Mikha Maria Sibi",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(123).padStart(3, "0"),
    name: "Richard mahesh george",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(124).padStart(3, "0"),
    name: "Muhammed Thameem",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(125).padStart(3, "0"),
    name: "Adrika Deepu",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(126).padStart(3, "0"),
    name: "Eshan",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(127).padStart(3, "0"),
    name: "Ayden Stephen",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  },
  {
    studentCode: "XST-SEED-" + String(128).padStart(3, "0"),
    name: "Mohammed Jahiz",
    guardianName: "Placeholder Guardian",
    whatsappNumber: "0000000000",
    grade: "10",
    board: "CBSE",
    medium: "English",
    country: "India",
    timeZone: "Asia/Kolkata",
    status: "ACTIVE"
  }
    ]
  });
  console.log("✅ Seeded Students.");

  console.log(
    process.env.NODE_ENV === "production"
      ? "🎉 Initialisation complete. Sign in as admin@xellotuition.com with the SEED_ADMIN_PASSWORD value, then change it under My Account."
      : `🎉 Initialisation complete. Local sign-in: admin@xellotuition.com / ${password === "demo123" ? "demo123" : "(SEED_ADMIN_PASSWORD)"}`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
